# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  ado-bench-benchmarks:
    dependencies:
    - base
    - ado-bench
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Benchmarks of code that utilize the ApplicativeDo language extension.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: aaronfriel/ado-bench
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Aaron Friel
name: ado-bench
synopsis: Benchmarks of code that utilize the ApplicativeDo language extension.
tests:
  ado-bench-test-suite:
    dependencies:
    - base
    - ado-bench
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
